# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FOTF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FOTF
  pod 'Firebase/Core'

  target 'FOTFTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
